version: "3.9"

services:
  billing-engine-postgres:
    image: postgres:17
    container_name: billing-engine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: billing_engine
    volumes:
      - billing_engine_postgres_pgdata:/var/lib/postgresql/data
    networks:
      - db_net
      - monitoring_net
      - discovery_net

  billing-engine-redis:
    image: redis:7.4
    container_name: billing-engine-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - billing_engine_redis_data:/data
    networks:
      - redis_net
      - monitoring_net
      - discovery_net

  billing-engine-rpc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: billing-engine-rpc
      APP_ENV: boe
      APP_TYPE: rpc
    depends_on:
      - billing-engine-postgres
      - billing-engine-redis
    labels:
      - "service=billing-engine-rpc"
    networks:
      - backend_net
      - db_net
      - redis_net
      - monitoring_net
      - proxy_net
      - discovery_net

  billing-engine-http:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: billing-engine-http
      APP_ENV: boe
      APP_TYPE: http
    # ports:
    #   - "60002:8080"
    depends_on:
      - billing-engine-postgres
      - billing-engine-redis
    labels:
      - "service=billing-engine-http"
      - "traefik.enable=true"
      - "traefik.http.routers.billing-engine-http.service=billing-engine-http"
      - "traefik.http.routers.billing-engine-http.rule=Host(`billing-engine-http.localhost`)"
      - "traefik.http.services.billing-engine-http.loadbalancer.server.port=8080"
      - "traefik.http.routers.billing-engine-http.entrypoints=web"
    networks:
      - backend_net
      - db_net
      - redis_net
      - monitoring_net
      - proxy_net
      - discovery_net

volumes:
  billing_engine_postgres_pgdata:
  billing_engine_redis_data:

networks:
  backend_net:
    external: true
  db_net:
    external: true
  redis_net:
    external: true
  monitoring_net:
    external: true
  proxy_net:
    external: true
  discovery_net:
    external: true
