app_name: billing-engine
env: prod
rpc_port: 8888
http_port: 8080
health_check_port: 5000

consul:
  host: consul
  port: 8500

db:
  driver: postgres
  host: billing-engine-postgres
  port: 5432
  user: postgres
  password: 123123
  db_name: billing_engine
  max_open_conns: 100
  max_idle_conns: 50
  max_conn_lifetime: 120
  max_conn_idle_time: 30

redis:
  host: billing-engine-redis
  port: 6379
  password: ""
  db: 0
